# Generated by Django 4.0.2 on 2022-02-26 08:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SBBCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=128)),
                ('template_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SBBGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SBBGameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game_data.sbbgame')),
            ],
        ),
        migrations.CreateModel(
            name='SBBHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=128)),
                ('template_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SBBPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SBBSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=128)),
                ('template_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SBBTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=128)),
                ('template_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SBBGameTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hp', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('exp', models.IntegerField(null=True)),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game_data.sbbhero')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game_data.sbbgameparticipant')),
            ],
        ),
        migrations.AddField(
            model_name='sbbgameparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game_data.sbbplayer'),
        ),
        migrations.AddConstraint(
            model_name='sbbgameturn',
            constraint=models.CheckConstraint(check=models.Q(('exp__gte', 0)), name='exp_floor'),
        ),
        migrations.AddConstraint(
            model_name='sbbgameturn',
            constraint=models.CheckConstraint(check=models.Q(('exp__lt', 3)), name='exp_cap'),
        ),
        migrations.AddConstraint(
            model_name='sbbgameparticipant',
            constraint=models.CheckConstraint(check=models.Q(('placement__gte', 1)), name='place_min'),
        ),
        migrations.AddConstraint(
            model_name='sbbgameparticipant',
            constraint=models.CheckConstraint(check=models.Q(('placement__lte', 8)), name='place_max'),
        ),
    ]
