# Generated by Django 4.0.3 on 2022-04-01 23:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBBGameCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField()),
                ('health', models.IntegerField()),
                ('golden', models.BooleanField()),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('base_character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_data.sbbcharacter')),
            ],
        ),
        migrations.CreateModel(
            name='SBBGameSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('base_spell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_data.sbbspell')),
            ],
        ),
        migrations.AddField(
            model_name='sbbgameturn',
            name='characters',
            field=models.ManyToManyField(through='game_data.SBBGameCharacter', to='game_data.sbbcharacter'),
        ),
        migrations.AddField(
            model_name='sbbgameturn',
            name='spells',
            field=models.ManyToManyField(through='game_data.SBBGameSpell', to='game_data.sbbspell'),
        ),
        migrations.AddField(
            model_name='sbbgameturn',
            name='treasures',
            field=models.ManyToManyField(to='game_data.sbbtreasure'),
        ),
        migrations.AlterField(
            model_name='sbbgameparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.sbbgame'),
        ),
        migrations.AlterField(
            model_name='sbbgameparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_data.sbbplayer'),
        ),
        migrations.AlterField(
            model_name='sbbgameturn',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game_data.sbbhero'),
        ),
        migrations.AlterField(
            model_name='sbbgameturn',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.sbbgameparticipant'),
        ),
        migrations.AddField(
            model_name='sbbgamespell',
            name='game_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.sbbgameturn'),
        ),
        migrations.AddField(
            model_name='sbbgamecharacter',
            name='game_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_data.sbbgameturn'),
        ),
    ]
