# Generated by Django 4.0.2 on 2022-04-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0002_sbbgamecharacter_sbbgamespell_sbbgameturn_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbbgame',
            name='player_list',
            field=models.ManyToManyField(through='game_data.SBBGameParticipant', to='game_data.SBBPlayer'),
        ),
        migrations.AddField(
            model_name='sbbplayer',
            name='possibly_mythic',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sbbgameturn',
            name='characters',
            field=models.ManyToManyField(through='game_data.SBBGameCharacter', to='game_data.SBBCharacter'),
        ),
        migrations.AlterField(
            model_name='sbbgameturn',
            name='spells',
            field=models.ManyToManyField(through='game_data.SBBGameSpell', to='game_data.SBBSpell'),
        ),
        migrations.AlterField(
            model_name='sbbgameturn',
            name='treasures',
            field=models.ManyToManyField(to='game_data.SBBTreasure'),
        ),
        migrations.AlterField(
            model_name='sbbplayer',
            name='account_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
